#!/bin/bash
command=$1

run_containers(){
  if [ "$1" = "bg" ]; then
    echo "Creating containers ..."
    sudo docker-compose up -d
  else
    echo "Listening on port 8080 ..."
    sudo docker-compose up
  fi
}

import_database(){
  echo "Importing data to the MySQL ..."
  sudo docker exec -i rdontheroadsite_mysql mysql -u root -pwp wordpress < rdontheroad-dump.sql
  echo "Change URLs on wordpress ..."
  sudo docker exec -i rdontheroadsite_mysql mysql -u root -pwp wordpress < rdontheroad-scripts.sql
}

clean_database(){
  echo "Removing MySQL data ..."
  sudo docker exec -i rdontheroadsite_mysql mysql -u root -pwp -e "DROP DATABASE wordpress"
  echo "Creating database ..."
  sudo docker exec -i rdontheroadsite_mysql mysql -u root -pwp -e "CREATE DATABASE wordpress"
}

extracting_plugins(){
  echo "Downloading plugins from Amazon ..."
  sudo curl -O https://s3.amazonaws.com/rd-marketing-objects/utils/wordpress-plugins/rdontheroadsite_plugins.zip
  sudo unzip rdontheroadsite_plugins.zip -d ./wp-content/plugins
  sudo rm rdontheroadsite_plugins.zip
}

active_multisite(){
  sudo chmod 777 .htaccess && sudo chmod 777 wp-config.php
  echo "Activing wordpress network ..."
  ex -sc "81i|define('WP_ALLOW_MULTISITE', true);" -cx wp-config.php && ex -sc "82i|define('MULTISITE', true);" -cx wp-config.php && ex -sc "83i|define('SUBDOMAIN_INSTALL', false);" -cx wp-config.php && ex -sc "84i|define('DOMAIN_CURRENT_SITE', 'localhost:8080');" -cx wp-config.php && ex -sc "85i|define('PATH_CURRENT_SITE', '/');" -cx wp-config.php && ex -sc "86i|define('SITE_ID_CURRENT_SITE', 1);" -cx wp-config.php && ex -sc "87i|define('BLOG_ID_CURRENT_SITE', 1);" -cx wp-config.php
  echo "RewriteEngine On" > .htaccess && echo "RewriteBase /" >> .htaccess && echo "RewriteRule ^index\.php$ - [L]" >> .htaccess && echo "RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ \$1wp-admin/ [R=301,L]" >> .htaccess && echo "RewriteCond %{REQUEST_FILENAME} -f [OR]" >> .htaccess && echo "RewriteCond %{REQUEST_FILENAME} -d" >> .htaccess && echo "RewriteRule ^ - [L]" >> .htaccess && echo "RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) \$2 [L]" >> .htaccess && echo "RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ \$2 [L]" >> .htaccess && echo "RewriteRule . index.php [L]" >> .htaccess
}

pull_images(){
  sudo docker-compose pull mysql
  sudo docker-compose pull wordpress
}

remove_containers(){
  echo "Removing containers ..."
  sudo docker rm rdontheroadsite_mysql
  sudo docker rm rdontheroadsite_wordpress
}

stop_containers(){
  echo "Stopping containers ..."
  sudo docker stop rdontheroadsite_mysql
  sudo docker stop rdontheroadsite_wordpress
}

case "$command" in
  install)
    pull_images
    exit 0
    ;;
  build)
    run_containers "bg"
    sleep 15
    extracting_plugins
    active_multisite
    import_database
    stop_containers
    echo "Containers have been built successfully! Type \"./rd-sites serve\" to start server"
    exit 0
    ;;
  serve)
    run_containers "none"
    exit 0
    ;;
  stop)
    stop_containers
    exit 0
    ;;
  rm)
    stop_containers
    remove_containers
    exit 0
    ;;
  rebuild)
    stop_containers
    remove_containers
    run_containers "bg"
    sleep 15
    extracting_plugins
    active_multisite
    import_database
    stop_containers
    echo "Containers have been built successfully! Type \"./rd-sites serve\" to start server"
    exit 0
    ;;
  db:clean)
    clean_database
    exit 0
    ;;
  db:import)
    import_database
    exit 0
    ;;
  db:reset)
    clean_database
    import_database
    exit 0
    ;;
  *)
    echo "Command not found"
    exit 1
    ;;
esac
